name: Android Lint

on:
  pull_request:
    path:
    - AndroidApp

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
    - name: Build with Gradle
      run: ./gradlew lint
