name: Android Lint

on:
  pull_request:
    path:
    - AndroidApp

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '9.0.4' # The JDK version to make available on the path. Takes a whole or semver JDK version, or 1.x syntax (e.g. 1.8 => Jdk 8.x). To specify a specific version for JDK 8 or older use the following pattern (8.0.x)
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
    - name: Cache
      uses: actions/cache@v1
      with:
        path: AndroidApp/app/build/reports
        key: ${{ github.repository }}-${{ github.sha }}
        # restore-keys: ${{ github.repository }}-${{ github.sha }}
    - name: Build with Gradle
      run: ./gradlew app:lint
      working-directory: AndroidApp

  danger:
    needs: android-lint
    runs-on: ubuntu-latest
    steps:
    - name: Cache
      uses: actions/cache@v1
      with:
        path: AndroidApp/app/build/reports
        key: ${{ github.repository }}-${{ github.sha }}
        restore-keys: ${{ github.repository }}-${{ github.sha }}
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - uses: MeilCli/danger-action@v2
      with:
        plugins_file: 'Gemfile'
        danger_file: 'Dangerfile'
        danger_id: 'danger-pr'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: echo
      run: cat AndroidApp/app/build/reports/lint-results.xml
