name: CI

on:
  push:
    branches:
      - '**'  # Runs on push to any branch
  schedule:
    - cron: '50 6 * * *'  # Runs daily at 06:50 UTC (15:50 JST)
    - cron: '55 6 * * *'  # Runs daily at 06:50 UTC (15:50 JST)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: check envs 
        run: make check 
        env:
          SECRET_HOGE: ${{ secrets.SECRET_HOGE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}