name: Check context 

on: 
  pull_request:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: context 
      run: echo ${{ github.job }} 
    - name: context 
      run: echo ${{ github.run_id }} 



