name: Check context 

on: 
  pull_request:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: job 
      run: echo ${{ github.job }} 
    - name: run id 
      run: echo ${{ github.run_id }} 
    - name: PR numver
      run: echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }'



