name: CI

on: 
  push:
    branches:
      - master

jobs:
  debug:
    runs-on: macOS-latest
    steps:
    - name: ls -l /Applications
      run: ls -l /Applications
    - name: pwd
      run: pwd
    - name: ls -l
      run: ls -l
    - name: xcode-select
      run: xcode-select -p      
    - name: env
      run: env
    - name: echo
      run: echo ${GITHUB_WORKSPACE}
  build:
    runs-on: macOS-latest
    steps:
    - name: pod install
      run: make -C ${GITHUB_WORKSPACE} install
    - name: start testing
      run: make -C ${GITHUB_WORKSPACE} PLATFORM=gha test

