name: CI

on: 
  push:
    branches:
      - master

jobs:
  debug:
    runs-on: macOS-latest
    steps:
    - name: ls 
      run: ls -l /Applications
    - name: xcode-select
      run: xcode-select -p      
  build:
    runs-on: macOS-latest
    steps:
    - name: pod install
      run: make install
    - name: start testing
      run: make PLATFORM=gha test

