name: Check syntax

on: 
  push:

jobs:
  debug:
    runs-on: macOS-latest
    env:
      DEBUG: 1
    steps:
    - name: line break
      run: |
        echo hoge && \
        echo fuga
    - name: check if
      if: true
      run: echo true
    - name: check debug flag
      if: ${{ env.DEBUG }}
      run: echo "DEBUG is 1"
